name: Tests

on:
  push:
    branches:
    - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
        - "2.5.9"
        - "2.6.10"
        - "2.7.8"
        - "3.0.7"
        - "3.1.7"
        - "3.2.8"
        - "3.3.8"
        - "3.4.4"
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install dependencies (older Ruby)
      if: matrix.ruby < 3.0
      run: bundle install --without development

    - name: Install dependencies (modern Ruby)
      if: matrix.ruby >= 3.0
      run: bundle install

    - name: Run tests only (older Ruby)
      if: matrix.ruby < 3.0
      run: bundle exec rake test

    - name: Run tests and linting (modern Ruby)
      if: matrix.ruby >= 3.0
      run: bundle exec rake
